"""Curated activities are content, never fabricated user data."""


def activity(key, title, kind, category, minutes, benefit, steps, tags, audio_url=None, artwork_url=None):
    res = dict(
        id=key,
        title=title,
        type=kind,
        category=category,
        minutes=minutes,
        benefit=benefit,
        steps=steps,
        tags=tags,
        level="All levels",
    )
    if audio_url:
        res["audio_url"] = audio_url
    if artwork_url:
        res["artwork_url"] = artwork_url
    return res




CATALOG = [
    activity(
        "breathing-3",
        "A little room to breathe",
        "breathing",
        "Mind",
        3,
        "A gentle pause when the workday feels full.",
        [
            "Sit comfortably and let your shoulders drop.",
            "Breathe in gently for four counts. Breathe out for six.",
            "Use your natural rhythm if counting feels uncomfortable. Stop if you feel dizzy.",
            "Notice one thing you can leave for later.",
        ],
        ["calm", "stress", "meetings"],
    ),
    activity(
        "grounding-2",
        "Come back to this moment",
        "grounding",
        "Mind",
        2,
        "Turn your attention toward your surroundings.",
        [
            "Feel your feet against the floor.",
            "Name five things you see, four you feel, and three you hear.",
            "Notice two scents and one taste, or simply notice your next breath.",
        ],
        ["overwhelmed", "calm"],
    ),
    activity(
        "meditation-5",
        "The quiet between tasks",
        "meditation",
        "Mind",
        5,
        "Make space for a calmer next step.",
        [
            "Find a comfortable seat. Keep your eyes open or softly closed.",
            "Notice your natural breath without changing it.",
            "When a thought appears, acknowledge it and return to breathing.",
            "Feel your feet, look around, and ease back into your day.",
        ],
        ["calm", "stress"],
    ),
    activity(
        "meditation-10",
        "One thing at a time",
        "meditation",
        "Focus",
        10,
        "Practice bringing your attention back gently.",
        [
            "Settle into your seat and put distractions aside.",
            "Choose your breath as an anchor.",
            "Count each exhale up to ten, then begin again.",
            "Losing count is fine. Begin again without judgment.",
            "Choose one manageable task to return to.",
        ],
        ["focus", "motivation"],
    ),
    activity(
        "meditation-ravi-shankar-10",
        "10-Min Meditation · Sri Sri Ravi Shankar",
        "meditation",
        "Deep Calm",
        10,
        "A sublime bilingual guided meditation on breath, inner stillness, and expanding consciousness with Gurudev Sri Sri Ravi Shankar.",
        [
            "Sit comfortably with spine erect, loosen shoulders, and gently close your eyes.",
            "Take a deep breath in, hold gently, and allow the breath to release on its own.",
            "Observe the stillness of your mind as breath pauses; let your entire body soften.",
            "Honor your body as a precious gift of nature made of trillions of cells.",
            "Feel the air inside and outside of you; breathe in and out with a gentle smile.",
            "Recognize your mind expanding like the vast open sky; repose peacefully in yourself.",
            "Om Shanti, Shanti, Shantihi. Gently open your eyes feeling deeply refreshed.",
        ],
        ["meditation", "calm", "relaxation", "peace", "ravi shankar", "breathing"],
        audio_url="/audio/meditations/ravi_shankar_10min.mp3",
        artwork_url="/images/meditation-ravi-shankar.png",
    ),
    activity(
        "meditation-choa-kok-sui-27",
        "Daily 30-Min Mind Refreshing · Master Choa Kok Sui",
        "meditation",
        "Energy & Healing",
        27,
        "Grand Master Choa Kok Sui's extremely powerful Twin Hearts Meditation for deep peace, illumination, blessing the Earth, and daily mind rejuvenation.",
        [
            "Sit comfortably with an erect spine, connect tongue to palate, and invoke divine blessings.",
            "Recall a happy event and smile with tenderness at your heart center.",
            "Smile at your crown center and feel it responding with divine love and sweetness.",
            "Raise your hands and bless the Earth with the prayer of Saint Francis of Assisi.",
            "Where there is hatred sow love; where injury, pardon; where despair, hope; where darkness, light.",
            "Bless every person and being on Earth with divine light, love, kindness, and joy.",
            "Chant the sacred mantra OM and meditate on the interval of stillness between the OMs.",
            "Release excess energy by blessing the Earth, and gently ground through feet and base of spine.",
            "Give thanks in full faith and gently open your eyes with a big smile.",
        ],
        ["meditation", "calm", "relaxation", "peace", "master choa kok sui", "twin hearts", "healing", "energy"],
        audio_url="/audio/meditations/choa_kok_sui_27min.mp3",
        artwork_url="/images/meditation-master.png",
    ),
    activity(
        "stretch-3",
        "Unfold your afternoon",
        "movement",
        "Body",
        3,
        "A comfortable movement break from sitting.",
        [
            "Stand if comfortable, or stay seated.",
            "Gently roll your shoulders and open your hands.",
            "Reach within a comfortable range. Avoid painful movements.",
            "Look away from the screen before returning.",
        ],
        ["energy", "meetings"],
    ),
    activity(
        "walk-5",
        "A change of scenery",
        "walk",
        "Environment",
        5,
        "A short walk at your own pace.",
        [
            "Choose a safe, accessible route indoors or outside.",
            "Put your screen away while walking.",
            "Notice light, shapes, or sounds along the way.",
            "Return when you feel ready.",
        ],
        ["energy", "break"],
    ),
    activity(
        "music-5",
        "Let the day settle",
        "music",
        "Mind",
        5,
        "Listen to a track you enjoy with full attention.",
        [
            "Choose a favorite song, or use the optional ambient sound.",
            "Set a comfortable volume.",
            "Notice the rhythm and the space between sounds.",
            "Let the final notes fade before returning.",
        ],
        ["calm", "motivation"],
    ),
    activity(
        "focus-5",
        "Find your next small win",
        "focus",
        "Focus",
        5,
        "Make the next task feel approachable.",
        [
            "Write down what is competing for your attention.",
            "Choose one task that can begin in two minutes.",
            "Close one unnecessary tab or distraction.",
            "Take the first small step. Progress can be modest.",
        ],
        ["focus", "motivation", "deadlines"],
    ),
    activity(
        "connection-3",
        "A moment of connection",
        "social",
        "Social",
        3,
        "Make room for support from someone you trust.",
        [
            "Think of someone you feel comfortable contacting.",
            "Draft a simple message: Do you have time for a quick catch-up?",
            "Choose whether to send it yourself. MoodMentor will not send it.",
            "If now is not a good time, plan a later conversation.",
        ],
        ["connection", "lonely"],
    ),
    activity(
        "gratitude-2",
        "Notice something good",
        "journaling",
        "Mind",
        2,
        "Give a small positive moment your attention.",
        [
            "Think of one ordinary thing you appreciated today.",
            "Name what made it meaningful.",
            "Hold that moment in mind; you do not have to feel grateful for everything.",
        ],
        ["gratitude", "motivation"],
    ),
    activity(
        "break-2",
        "Permission to pause",
        "break",
        "Recovery",
        2,
        "Step away from constant input.",
        [
            "Look away from your screen.",
            "Take a sip of water if you want.",
            "Relax your hands and shoulders.",
            "Decide whether you need more rest before returning.",
        ],
        ["break", "meetings", "energy"],
    ),
    activity(
        "game-2",
        "Find five little details",
        "game",
        "Mind",
        2,
        "A playful attention reset with your surroundings.",
        [
            "Find something round, something green, and something soft.",
            "Find a repeating pattern nearby.",
            "Notice one small detail you had not seen before.",
        ],
        ["focus", "break"],
    ),
]
BY_ID = {a["id"]: a for a in CATALOG}
